package com.fixgo.shared.storage;

import java.util.Optional;

/**
 * Where uploaded files live. PUBLIC objects (scene photos) are reachable by URL; PRIVATE objects (KYC identity
 * documents) are never exposed by URL: only the backend reads them, for admins (docs/api.md).
 * Keys are generated by the backend ({@link StorageKeys}); callers never pass raw client input to a storage.
 */
public interface ObjectStorage {
    enum Visibility { PUBLIC, PRIVATE }

    record StoredObject(byte[] bytes, String contentType) { }

    void put(Visibility visibility, String key, byte[] bytes, String contentType);

    Optional<StoredObject> get(Visibility visibility, String key);

    boolean exists(Visibility visibility, String key);

    /** Absolute URL of a PUBLIC object. */
    String publicUrl(String key);
}
